apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: idca5rx8k-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:494b54f7f95f41e84fd81a5eb76fa4cd1c2916fa@sha256:74ff87c926d092d02de8e8372ac4c788fa10c809a9e59ba971e345c846aacb11
          name: container-image
